//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetrixPeDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_rol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_rol()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public int id_rol { get; set; }
        public string sigla_rol { get; set; }
        public string cod_rol { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public string cod_usuario_crea { get; set; }
        public string cod_usuario_modifica { get; set; }
        public string cod_usuario_elimina { get; set; }
        public string cod_aplicacion_crea { get; set; }
        public string cod_aplicacion_modifica { get; set; }
        public string cod_aplicacion_elimina { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
